language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm install istanbul mocha -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm test
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "uGN5mjxRBC8ahziLkokIH2DK4xWaxMfMFPSqiymFbGYGx2igZltGbe5JCdg9pd4XzgoEMszYHkaS1UDq4cyJlxlkv7X5E2Cq6gut8TEno75Zliwa1dYiQhp/FSxB6VhE2EaLmyocaZKRBbnCsROeidw1RMgbEOHSuaU2Q6MvQ+p79JPGt8z4PBBpeZ46D5ZIhUFB4DOsWKQ78I4Vu7IMI9w6jMoxF2l+zfwRTFaj+voTenxDcMXegyM7NzIlES+03MYLkiYydxmpjLiCK5zcSElGAIE8LpU0ei8GVcuXzTdU9N7Q2OMQ9rpR+BCESDY7RHF9doff5lopfAWGAR6MdklXcZOuiF7StAwGTWfK3A+wbqkheHcDBakysPbLkCuyNX45DxVCUsZhyrvA9TzKaWkt2QUg4asg8jjBF0tdcgxg7yD1BklLADCvtUf4J+dbrO7dczaXEQqNPEeQYBw65Kwf79kil1hSk7/AGLXc6a20u5UZ42ql1EUm/7QymIaJC5cNVjWD0lJb+P/0puXcmwlHucLDxGaAc7AdsvhmSsqvpNy70iWSpons1Er4HtHhXs9ma55EVMAAuZdvoGBCT3oMu5ArjqNPcmz5NA4hubsJZ4pOxM0N71thaLsk/iKerMuiarSW7aavjLzq9SASF37+UOy/Qp6zxcSMNzRKyTo="
