language: node_js
node_js:
- '6'
addons:
  firefox: "43.0"
before_install:
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
- npm install istanbul mocha -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install
script:
- npm test
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js
env:
  secure: "rplMLybdTuUUfE/TV9W8B+psn44hh3bXZd6KddnygrZhQ7yu/qpGNKABLOMkvnVFAk+21wAMhuKJtmxtqcV+XdDk4ETRozKTgTM+dTRNSXmaeLbMSh9iFfQaYgL+p/4FpTO7T7JuxaTWlafhXGW3/sqjcWZnZfyXMQvsw8rh29n5l1bf7gMUW7WCRoCY+Hq0LLsjaap07ctIvdbQAaY4IBglbsyCm/sVUVnPsesColeNjKbLr3mRu5Ue3eCEaVwTml+jC22iiE82glvYAGqQK+8H+7a+AIxICHD8vRTovewzsg857ltWucfey2XcaADMHBtQpzpzq6KmtI4+JJEyH5rxBHKJv1MjzCcbAt3M3dDkVTOmNmz3mIffCMi39mW1z0kTL9k1HYmeGmd8p/yVGiKyfJiO/+GQXeg2NFybFTUfFSwiHgTKKnnUvRM+E3YZ/opvrB+4TovMu2/I1Ybs0D+wwGrA97Vup6Z30fxcVTjnfU9FiSW6My4yGzwjf3kVkT/DAtnWUWhjPUaq2oDGbLDgqbGaPzRGWWTCz7w1cd6I6bS3NGvwOQsy7VnbKZEvhFoQkYrcsLE+lXgIkUqTB7RLAkTZMAkX+mm/DC4eXXCg9GF0dKJCtEIk8lNYeJJrzdSWnLDbSyop2lT23NJsApiunQoBBbA4rBU9Sm6RDa4="
